name: Test Feature Branch

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"

jobs:
  test:
    uses: ./.github/workflows/jest.yml
    secrets: inherit
  typescript:
    uses: "./.github/workflows/build.yml"
    secrets: inherit
